version: '3.8'

services:
  app:
    image: oyaga/nakawoot:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      
      # Database Config (Conectando ao supabase_db da rede AikaNet)
      DB_HOST: "supabase_db"
      DB_PORT: "5432"
      DB_USER: "supabase_admin"
      DB_PASSWORD: "0f30252de114094b71d49f657f5776dd"
      DB_NAME: "postgres"
      DB_SSLMODE: "disable"
      
      # Supabase Config
      SUPABASE_URL: "http://supabase_kong:8000"
      SUPABASE_JWT_SECRET: "02ed0e4fd27f8d662016a0d9bb495fcdd0c90d7f"
      SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogInNlcnZpY2Vfcm9sZSIsCiAgImlzcyI6ICJzdXBhYmFzZSIsCiAgImlhdCI6IDE3MTUwNTA4MDAsCiAgImV4cCI6IDE4NzI4MTcyMDAKfQ.vi4I60GYr6zSeGUjcuI-iu-YY7gSq2yqOvnGK2rMv8k"
      SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogImFub24iLAogICJpc3MiOiAic3VwYWJhc2UiLAogICJpYXQiOiAxNzE1MDUwODAwLAogICJleHAiOiAxODcyODE3MjAwCn0.p97SPDUBrtdz7FOYcnCWcsSp0a2ebATVgbNM9xOy4Xg"
      
      # Storage Config
      USE_SUPABASE_STORAGE: "true"
      SUPABASE_STORAGE_BUCKET: "mensager-media"
      
      # Frontend Path (Internal)
      FRONTEND_PATH: "/app/manager/dist"
      
      # URL pública para acesso a mídias (Ajuste para seu domínio real se necessário)
      MEDIA_BASE_URL: "https://nakawoot.aikanakamura.com/media"

    networks:
      - AikaNet

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/api/v1/health"]
      interval: 10s
      timeout: 3s
      retries: 10

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.nakawoot.rule=Host(`nakawoot.aikanakamura.com`)
        - traefik.http.services.nakawoot.loadbalancer.server.port=8080
        - traefik.http.routers.nakawoot.service=nakawoot
        - traefik.http.routers.nakawoot.entrypoints=websecure
        - traefik.http.routers.nakawoot.tls.certresolver=letsencryptresolver
        - traefik.http.routers.nakawoot.tls=true
        - traefik.docker.network=AikaNet
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 200M

networks:
  AikaNet:
    external: true
    name: AikaNet
